/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'khlee' at '16. 3. 25 오후 8:05' with Gradle 2.3
 *
 * @author khlee, @date 16. 3. 25 오후 8:05
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
